stages:
  - deploy
  - logs

deploy_job:
  stage: deploy
  script:
    - cd /var/data/www/turkmart-laravel
    - git fetch --all
    - git reset --hard origin/master
    - git pull origin master
    - php artisan optimize:clear
    - php artisan migrate
    - composer install
    - composer update
    - npm install
    - npm run ***
    - systemctl restart supervisord
  only:
    - main
  when: manual
  tags:
    - webserver

logs_job:
  stage: logs
  script:
    - tail -n 1000 /var/data/www/logs/laravel.log
    - tail -n 1000 /var/data/www/logs/mariadb.log
    - tail -n 1000 /var/data/www/logs/nginx_turkiyemart.com_access
    - tail -n 1000 /var/data/www/logs/nginx_turkiyemart.com_error
    - tail -n 1000 /var/data/www/logs/phpfpm-error.log
    - tail -n 1000 /var/data/www/logs/supervisor_log.log
  only:
    - main
  when: manual
  tags:
    - webserver
